## data
img_dir: dummydata/images/2d
point_type: S_Point
size_image: 520
train_path: dummydata/S_Point/2d/train.csv
val_path: dummydata/S_Point/2d/val.csv
test_path: dummydata/S_Point/2d/test.csv

# for ROI
mean_x: 991
mean_y: 952

n_dim: 2d
n_slice: 1

## model
# cnn_type: custom  
cnn_type: resnet18 
backbone_type: 2d


output_dim: 2
max_epochs: 100
lr: 1e-4
batch_size: 8
