## data
root_dir: dummydata
img_dir: images
point_type: S_Point
size_image: 520
train_path: dummydata/S_Point/train.csv
val_path: dummydata/S_Point/val.csv
test_path: dummydata/S_Point/test.csv

n_dim: 2d

## model
# cnn_type: custom  
cnn_type: resnet18 

output_dim: 2
max_epochs: 100
lr: 1e-4
batch_size: 8
